version: "3.9"

services:
  scheduler:
    image: ghcr.io/traewelling/traewelling:latest
    container_name: traewelling-scheduler
    restart: 'always'
    depends_on:
      - app
    networks:
      - internal
    env_file:
      - .env.docker
    environment:
      CONTAINER_ROLE: scheduler

  queue:
    image: ghcr.io/traewelling/traewelling:latest
    container_name: traewelling-queue
    restart: 'always'
    depends_on:
      - app
    networks:
      - internal
    env_file:
      - .env.docker
    environment:
      CONTAINER_ROLE: queue

  app:
    image: ghcr.io/traewelling/traewelling:latest
    container_name: traewelling-app
    restart: 'always'
    ports:
      - "80:80"
    networks:
      - internal
    env_file:
      - .env.docker
    environment:
      - CONTAINER_ROLE=app

  database:
    image: mariadb:10
    container_name: traewelling-db
    restart: 'always'
    command:
      - --max_allowed_packet=67108864      # Set max_allowed_packet to 256M (or any other value)
      - --innodb-buffer-pool-size=2G
      - --innodb-log-file-size=1G
    volumes:
      - ./docker/database:/var/lib/mysql
    networks:
      - internal
    environment:
      - TZ=Europe/Berlin
    ports:
      - "3306:3306"
    env_file:
      - .env.docker

networks:
  internal:
    external: false
